local M = {}

function M.load()
  vim.cmd("highlight clear")

  if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
  end

  vim.o.termguicolors = true
  vim.g.colors_name = "glimwick"

  local palette = require("glimwick.palette")
  local p = (vim.o.background == "light") and palette.taper or palette.ember
  local italics = vim.g.glimwick_italic ~= false
  local transparent = vim.g.glimwick_transparent == true

  local bg_base   = transparent and "NONE" or p.base
  local bg_panel  = p.mantle
  local bg_float  = p.crust
  local bg_inline = p.surface0

  local function hl(group, opts)
    if not italics then
      opts.italic = nil
    end
    vim.api.nvim_set_hl(0, group, opts)
  end

  hl("Normal",          { fg = p.text, bg = bg_base })
  hl("NormalNC",        { fg = p.text, bg = bg_base })
  hl("NormalFloat",     { fg = p.text, bg = bg_float })
  hl("FloatBorder",     { fg = p.overlay0, bg = bg_float })
  hl("FloatTitle",      { fg = p.gold, bg = bg_float, bold = true })
  hl("ColorColumn",     { bg = p.surface0 })
  hl("Cursor",          { fg = p.base, bg = p.gold })
  hl("CursorLine",      { bg = p.surface0 })
  hl("CursorColumn",    { bg = p.surface0 })
  hl("CursorLineNr",    { fg = p.gold, bold = true })
  hl("LineNr",          { fg = p.overlay0 })
  hl("SignColumn",      { fg = p.overlay0, bg = bg_base })
  hl("Folded",          { fg = p.subtext0, bg = p.surface0 })
  hl("FoldColumn",      { fg = p.overlay0, bg = bg_base })
  hl("VertSplit",       { fg = p.surface1 })
  hl("WinSeparator",    { fg = p.surface1 })
  hl("StatusLine",      { fg = p.subtext1, bg = bg_panel })
  hl("StatusLineNC",    { fg = p.overlay1, bg = bg_panel })
  hl("TabLine",         { fg = p.subtext0, bg = bg_inline })
  hl("TabLineFill",     { bg = bg_panel })
  hl("TabLineSel",      { fg = p.gold, bg = bg_inline, bold = true })
  hl("WinBar",          { fg = p.subtext1, bg = bg_base })
  hl("WinBarNC",        { fg = p.overlay1, bg = bg_base })
  hl("Visual",          { bg = p.surface1 })
  hl("VisualNOS",       { bg = p.surface1 })
  hl("Search",          { fg = p.base, bg = p.gold })
  hl("IncSearch",       { fg = p.base, bg = p.amber })
  hl("CurSearch",       { fg = p.base, bg = p.amber })
  hl("MatchParen",      { fg = p.amber, bg = p.surface1, bold = true })
  hl("Pmenu",           { fg = p.text, bg = p.surface0 })
  hl("PmenuSel",        { fg = p.text, bg = p.surface1, bold = true })
  hl("PmenuSbar",       { bg = p.surface1 })
  hl("PmenuThumb",      { bg = p.overlay0 })
  hl("WildMenu",        { fg = p.base, bg = p.gold })
  hl("Directory",       { fg = p.indigo })
  hl("Title",           { fg = p.gold, bold = true })
  hl("Question",        { fg = p.sage })
  hl("MoreMsg",         { fg = p.sage })
  hl("ModeMsg",         { fg = p.subtext1, bold = true })
  hl("ErrorMsg",        { fg = p.coral })
  hl("WarningMsg",      { fg = p.honey })
  hl("NonText",         { fg = p.surface2 })
  hl("Whitespace",      { fg = p.surface2 })
  hl("SpecialKey",      { fg = p.overlay0 })
  hl("EndOfBuffer",     { fg = p.surface0 })
  hl("Conceal",         { fg = p.overlay1 })
  hl("SpellBad",        { sp = p.coral, undercurl = true })
  hl("SpellCap",        { sp = p.honey, undercurl = true })
  hl("SpellLocal",      { sp = p.teal, undercurl = true })
  hl("SpellRare",       { sp = p.wisteria, undercurl = true })
  hl("QuickFixLine",    { bg = p.surface1, bold = true })

  hl("Comment",        { fg = p.subtext0, italic = true })
  hl("Constant",       { fg = p.persimmon })
  hl("String",         { fg = p.sage })
  hl("Character",      { fg = p.sage })
  hl("Number",         { fg = p.persimmon })
  hl("Float",          { fg = p.persimmon })
  hl("Boolean",        { fg = p.coral })
  hl("Identifier",     { fg = p.text })
  hl("Function",       { fg = p.amber })
  hl("Statement",      { fg = p.gold })
  hl("Conditional",    { fg = p.gold })
  hl("Repeat",         { fg = p.gold })
  hl("Label",          { fg = p.gold })
  hl("Operator",       { fg = p.subtext1 })
  hl("Keyword",        { fg = p.gold })
  hl("Exception",      { fg = p.coral })

  hl("PreProc",        { fg = p.wisteria })
  hl("Include",        { fg = p.wisteria })
  hl("Define",         { fg = p.wisteria })
  hl("Macro",          { fg = p.wisteria })
  hl("PreCondit",      { fg = p.wisteria })
  hl("Type",           { fg = p.fuji })
  hl("StorageClass",   { fg = p.fuji })
  hl("Structure",      { fg = p.fuji })
  hl("Typedef",        { fg = p.fuji })
  hl("Special",        { fg = p.teal })
  hl("SpecialChar",    { fg = p.teal })
  hl("Tag",            { fg = p.gold })
  hl("Delimiter",      { fg = p.subtext1 })
  hl("SpecialComment", { fg = p.subtext0, bold = true })
  hl("Debug",          { fg = p.coral })
  hl("Underlined",     { underline = true })
  hl("Bold",           { bold = true })
  hl("Italic",         { italic = true })
  hl("Error",          { fg = p.coral })
  hl("Todo",           { fg = p.base, bg = p.gold, bold = true })

  hl("@variable",                 { fg = p.text })
  hl("@variable.builtin",         { fg = p.coral, italic = true })
  hl("@variable.parameter",       { fg = p.persimmon })
  hl("@variable.member",          { fg = p.sakura })
  hl("@property",                 { fg = p.sakura })
  hl("@field",                    { fg = p.sakura })
  hl("@constant",                 { fg = p.persimmon })
  hl("@constant.builtin",         { fg = p.persimmon, italic = true })
  hl("@constant.macro",           { fg = p.wisteria })
  hl("@module",                   { fg = p.indigo })
  hl("@module.builtin",           { fg = p.indigo, italic = true })
  hl("@namespace",                { fg = p.indigo })
  hl("@string",                   { fg = p.sage })
  hl("@string.escape",            { fg = p.teal })
  hl("@string.regexp",            { fg = p.teal })
  hl("@string.special.url",       { fg = p.indigo, underline = true })
  hl("@character",                { fg = p.sage })
  hl("@number",                   { fg = p.persimmon })
  hl("@boolean",                  { fg = p.coral })
  hl("@function",                 { fg = p.amber })
  hl("@function.builtin",         { fg = p.teal })
  hl("@function.macro",           { fg = p.wisteria })
  hl("@function.method",          { fg = p.amber })
  hl("@constructor",              { fg = p.fuji })
  hl("@keyword",                  { fg = p.gold })
  hl("@keyword.function",         { fg = p.gold })
  hl("@keyword.operator",         { fg = p.gold })
  hl("@keyword.return",           { fg = p.gold, italic = true })
  hl("@keyword.import",           { fg = p.wisteria })
  hl("@keyword.exception",        { fg = p.coral })
  hl("@type",                     { fg = p.fuji })
  hl("@type.builtin",             { fg = p.fuji, italic = true })
  hl("@type.definition",          { fg = p.fuji })
  hl("@attribute",                { fg = p.wisteria })
  hl("@operator",                 { fg = p.subtext1 })
  hl("@punctuation.delimiter",    { fg = p.subtext1 })
  hl("@punctuation.bracket",      { fg = p.subtext1 })
  hl("@punctuation.special",      { fg = p.teal })
  hl("@tag",                      { fg = p.gold })
  hl("@tag.attribute",            { fg = p.persimmon })
  hl("@tag.delimiter",            { fg = p.subtext1 })
  hl("@comment",                  { fg = p.subtext0, italic = true })
  hl("@comment.todo",             { fg = p.base, bg = p.gold, bold = true })
  hl("@comment.error",            { fg = p.base, bg = p.coral, bold = true })
  hl("@comment.warning",          { fg = p.base, bg = p.honey, bold = true })
  hl("@comment.note",             { fg = p.base, bg = p.teal, bold = true })
  hl("@markup.heading",           { fg = p.gold, bold = true })
  hl("@markup.strong",            { bold = true })
  hl("@markup.italic",            { italic = true })
  hl("@markup.strikethrough",     { fg = p.plum, strikethrough = true })
  hl("@markup.link",              { fg = p.indigo })
  hl("@markup.link.url",          { fg = p.indigo, underline = true })
  hl("@markup.raw",               { fg = p.sage })
  hl("@markup.quote",             { fg = p.subtext1, italic = true })
  hl("@markup.list",              { fg = p.gold })
  hl("@diff.plus",                { fg = p.sage })
  hl("@diff.minus",               { fg = p.coral })
  hl("@diff.delta",               { fg = p.honey })

  hl("@lsp.type.class",          { link = "@type" })
  hl("@lsp.type.interface",      { link = "@type" })
  hl("@lsp.type.struct",         { link = "@type" })
  hl("@lsp.type.enum",           { link = "@type" })
  hl("@lsp.type.enumMember",     { link = "@constant" })
  hl("@lsp.type.function",       { link = "@function" })
  hl("@lsp.type.method",         { link = "@function.method" })
  hl("@lsp.type.macro",          { link = "@function.macro" })
  hl("@lsp.type.namespace",      { link = "@module" })
  hl("@lsp.type.parameter",      { link = "@variable.parameter" })
  hl("@lsp.type.property",       { link = "@property" })
  hl("@lsp.type.variable",       { link = "@variable" })
  hl("@lsp.type.keyword",        { link = "@keyword" })
  hl("@lsp.type.decorator",      { link = "@attribute" })

  hl("DiagnosticError",           { fg = p.coral })
  hl("DiagnosticWarn",            { fg = p.honey })
  hl("DiagnosticInfo",            { fg = p.indigo })
  hl("DiagnosticHint",            { fg = p.teal })
  hl("DiagnosticOk",              { fg = p.sage })
  hl("DiagnosticUnderlineError",  { sp = p.coral, undercurl = true })
  hl("DiagnosticUnderlineWarn",   { sp = p.honey, undercurl = true })
  hl("DiagnosticUnderlineInfo",   { sp = p.indigo, undercurl = true })
  hl("DiagnosticUnderlineHint",   { sp = p.teal, undercurl = true })
  hl("DiagnosticVirtualTextError",{ fg = p.coral, bg = bg_inline })
  hl("DiagnosticVirtualTextWarn", { fg = p.honey, bg = bg_inline })
  hl("DiagnosticVirtualTextInfo", { fg = p.indigo, bg = bg_inline })
  hl("DiagnosticVirtualTextHint", { fg = p.teal, bg = bg_inline })
  hl("LspReferenceText",          { bg = p.surface1 })
  hl("LspReferenceRead",          { bg = p.surface1 })
  hl("LspReferenceWrite",         { bg = p.surface1, bold = true })
  hl("LspInlayHint",              { fg = p.overlay1, bg = bg_base, italic = true })

  hl("DiffAdd",         { bg = p.diff_add })
  hl("DiffDelete",      { fg = p.overlay0, bg = p.diff_delete })
  hl("DiffChange",      { bg = p.diff_change })
  hl("DiffText",        { bg = p.diff_text })
  hl("Added",           { fg = p.sage })
  hl("Removed",         { fg = p.coral })
  hl("DiagnosticDeprecated", { fg = p.plum, strikethrough = true })
  hl("Changed",         { fg = p.honey })
  hl("GitSignsAdd",     { fg = p.sage })
  hl("GitSignsChange",  { fg = p.honey })
  hl("GitSignsDelete",  { fg = p.coral })

  hl("TelescopeNormal",         { fg = p.text, bg = bg_float })
  hl("TelescopeBorder",         { fg = p.overlay0, bg = bg_float })
  hl("TelescopeTitle",          { fg = p.gold, bold = true })
  hl("TelescopeSelection",      { bg = p.surface0, bold = true })
  hl("TelescopeSelectionCaret", { fg = p.gold, bg = p.surface0 })
  hl("TelescopeMatching",       { fg = p.amber, bold = true })
  hl("TelescopePromptPrefix",   { fg = p.gold })
  hl("TelescopePromptNormal",   { fg = p.text, bg = bg_panel })
  hl("TelescopePromptBorder",   { fg = p.overlay0, bg = bg_panel })
  hl("TelescopePromptTitle",    { fg = p.gold, bold = true })
  hl("TelescopeResultsNormal",  { fg = p.text, bg = bg_float })
  hl("TelescopeResultsBorder",  { fg = p.overlay0, bg = bg_float })
  hl("TelescopeResultsTitle",   { fg = p.gold, bold = true })
  hl("TelescopePreviewNormal",  { fg = p.text, bg = bg_float })
  hl("TelescopePreviewBorder",  { fg = p.overlay0, bg = bg_float })
  hl("TelescopePreviewTitle",   { fg = p.sage, bold = true })

  hl("BlinkCmpMenu",                         { fg = p.text, bg = bg_float })
  hl("BlinkCmpMenuBorder",                   { fg = p.overlay0, bg = bg_float })
  hl("BlinkCmpMenuSelection",                { bg = p.surface1, bold = true })
  hl("BlinkCmpScrollBarThumb",               { bg = p.overlay0 })
  hl("BlinkCmpScrollBarGutter",              { bg = p.surface0 })
  hl("BlinkCmpLabel",                        { fg = p.text })
  hl("BlinkCmpLabelMatch",                   { fg = p.amber, bold = true })
  hl("BlinkCmpLabelDeprecated",              { fg = p.plum, strikethrough = true })
  hl("BlinkCmpLabelDetail",                  { fg = p.subtext0 })
  hl("BlinkCmpLabelDescription",             { fg = p.subtext0 })
  hl("BlinkCmpGhostText",                    { fg = p.overlay1, italic = true })
  hl("BlinkCmpDoc",                          { fg = p.text, bg = bg_float })
  hl("BlinkCmpDocBorder",                    { fg = p.overlay0, bg = bg_float })
  hl("BlinkCmpDocSeparator",                 { fg = p.overlay0, bg = bg_float })
  hl("BlinkCmpSignatureHelp",                { fg = p.text, bg = bg_float })
  hl("BlinkCmpSignatureHelpBorder",          { fg = p.overlay0, bg = bg_float })
  hl("BlinkCmpSignatureHelpActiveParameter", { fg = p.amber, bold = true })
  hl("BlinkCmpKind",                         { fg = p.subtext1 })
  hl("BlinkCmpKindFunction",                 { fg = p.amber })
  hl("BlinkCmpKindMethod",                   { fg = p.amber })
  hl("BlinkCmpKindVariable",                 { fg = p.text })
  hl("BlinkCmpKindKeyword",                  { fg = p.gold })
  hl("BlinkCmpKindClass",                    { fg = p.fuji })
  hl("BlinkCmpKindInterface",                { fg = p.fuji })
  hl("BlinkCmpKindStruct",                   { fg = p.fuji })
  hl("BlinkCmpKindEnum",                     { fg = p.fuji })
  hl("BlinkCmpKindEnumMember",               { fg = p.persimmon })
  hl("BlinkCmpKindModule",                   { fg = p.indigo })
  hl("BlinkCmpKindProperty",                 { fg = p.sakura })
  hl("BlinkCmpKindField",                    { fg = p.sakura })
  hl("BlinkCmpKindConstant",                 { fg = p.persimmon })
  hl("BlinkCmpKindSnippet",                  { fg = p.wisteria })
  hl("BlinkCmpKindText",                     { fg = p.subtext1 })

  hl("MiniIconsAzure",  { fg = p.fuji })
  hl("MiniIconsBlue",   { fg = p.indigo })
  hl("MiniIconsCyan",   { fg = p.teal })
  hl("MiniIconsGreen",  { fg = p.sage })
  hl("MiniIconsGrey",   { fg = p.subtext1 })
  hl("MiniIconsOrange", { fg = p.amber })
  hl("MiniIconsPurple", { fg = p.plum })
  hl("MiniIconsRed",    { fg = p.coral })
  hl("MiniIconsYellow", { fg = p.gold })

  hl("FidgetTitle", { fg = p.gold, bold = true })
  hl("FidgetTask",  { fg = p.subtext0 })

  hl("WhichKey",          { fg = p.gold })
  hl("WhichKeyGroup",     { fg = p.indigo })
  hl("WhichKeyDesc",      { fg = p.text })
  hl("WhichKeySeparator", { fg = p.overlay0 })

  local light = vim.o.background == "light"
  vim.g.terminal_color_0  = light and p.subtext1 or p.surface1
  vim.g.terminal_color_8  = light and p.subtext0 or p.overlay0
  vim.g.terminal_color_7  = light and p.surface2 or p.subtext1
  vim.g.terminal_color_15 = light and p.surface1 or p.text
  vim.g.terminal_color_1  = p.coral
  vim.g.terminal_color_9  = p.persimmon
  vim.g.terminal_color_2  = p.sage
  vim.g.terminal_color_10 = p.moss
  vim.g.terminal_color_3  = p.gold
  vim.g.terminal_color_11 = p.honey
  vim.g.terminal_color_4  = p.indigo
  vim.g.terminal_color_12 = p.fuji
  vim.g.terminal_color_5  = p.plum
  vim.g.terminal_color_13 = p.wisteria
  vim.g.terminal_color_6  = p.teal
  vim.g.terminal_color_14 = p.teal
end

return M
